#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

#define PI 3.141592653589793238462643383279
#define e 2.7182818284590452353602874713527
#define std_deviation 3.5
#define mean 6
#define n 3

#ifndef RAND_MAX
#define RAND_MAX 0x7fffffff
#endif

float clt_sum = 0;
float clt_mean;
float clt_variance;
float clt_std_deviation;
float clt_expected_value;
float clt_result = 0;
float array[n];
float randomNumberGenerator() {
  return (rand() + 1.0) / (RAND_MAX + 1.0);
}

float boxMuller(float mu, float ss) {
  srand(time(0));
  float x = randomNumberGenerator();
  float carpan;
  carpan = 1/sqrt(2*PI*ss*ss);
  return carpan* pow(e, (-1*(x - mu) * (x - mu) / (2*ss*ss)));
}

float centralLimitTheorem() {
  for(int i=0; i<=n-1;i++){ 
    array[i] =  randomNumberGenerator();
    srand(time(0));
    clt_sum += array[i];
  }
 clt_mean = clt_sum/n;
 for (int z = 0; z < n-1; z++){
    clt_variance +=  + pow((array[z] - clt_mean), 2);
 }
 for(int c = 0; c<=n-1;c++){
    clt_expected_value += array[c] * array[c]/n;
 }
 clt_std_deviation = sqrt(clt_variance);

 clt_result = (clt_mean - clt_expected_value) / (clt_std_deviation/sqrt(n));

 printf(" random number generated by central limit theorem algorithm: %f",clt_result);
 }



int main(){
 printf("random number generated by box-muller algorithm:  %f",
 boxMuller(mean,std_deviation));
 centralLimitTheorem();
}
